spring:
  datasource:
    username: root
    hikari:
        maximum-pool-size: 5
        connection-timeout: 20000
    url: jdbc:mysql://localhost:3306/ClienteData?useSSL=false
    password: sql12345
    
    
    #driver-class-name: com.mysql.cj.jdbc.Driver
  #application:
    #name: Client
  #jpa:
    #hibernate:
      #ddl-auto: update
#server:
  #port: 0
#eureka:
  #instance:
    #instance-id: ${spring.application.name}:${random.value}
  #client:
    #service-url:
      #defaultZone: http://localhost:8761/eureka/
